[project]
name = "random-species"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "linus", email = "linus@molteno.net" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "pydantic>=2.13.5",
    "sqlmodel>=0.0.42",
]

[project.scripts]
random-species = "random_species:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
